- Core:
    - Proxmox:
        icon: proxmox-light.png
        href: https://192.168.88.88:8006
        widget:
          type: proxmox
          url: https://192.168.88.88:8006
          username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
    - Portainer:
        icon: portainer.png
        href: https://192.168.88.180:9443
        server: docker
        container: portainer
        widget:
          type: portainer
          url: https://192.168.88.180:9443
          env: 2
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - OpenMediaVault:
        icon: openmediavault.png
        href: http://192.168.88.89
        description: NAS
        ping: http://192.168.88.89
- Media:
    - Emby:
        icon: emby.png
        href: http://192.168.88.180:8096
        server: docker
        container: emby
        widget:
            type: emby
            url: http://192.168.88.180:8096
            key: {{HOMEPAGE_VAR_EMBY_KEY}}
    - qBittorrent:
        icon: qbittorrent.png
        href: http://192.168.88.180:8080
        server: docker
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://192.168.88.180:8080
          username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
    - File Browser:
        icon: filebrowser.png
        href: http://192.168.88.180:8082
        description: /mnt/omv-torrent
        server: docker
        container: filebrowser
- Coin:
    - Coin Market Cap:
        icon: bitcoin.png
        widget:
          type: coinmarketcap
          currency: USD # Optional
          symbols: [BTC, UPX, BTT, STORJ]
          key: {{HOMEPAGE_VAR_COINMARKETCAP_KEY}}